### ISSUE TITLE
TypeError: (0 , _colormin2.default) is not a function

### ISSUE THREAD

**Issue by MarvinXu** [ben-eb/postcss-colormin#46]
`ERROR in ./~/css-loader?{"minimize":true,"sourceMap":true}!./~/vue-loader/lib/style-compiler?{"id":"data-v-409f
fe34","scoped":true,"hasInlineConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/component
s/Hello.vue
Module build failed: TypeError: (0 , _colormin2.default) is not a function
    at E:\gitlab\ZZY-Activities\node_modules\postcss-colormin\dist\index.js:63:49
    at E:\gitlab\ZZY-Activities\node_modules\postcss-colormin\dist\index.js:29:22
    at Array.forEach (native)
    at walk (E:\gitlab\ZZY-Activities\node_modules\postcss-colormin\dist\index.js:28:18)
    at transform (E:\gitlab\ZZY-Activities\node_modules\postcss-colormin\dist\index.js:48:5)
    at E:\gitlab\ZZY-Activities\node_modules\postcss-colormin\dist\index.js:74:20
    at E:\gitlab\ZZY-Activities\node_modules\postcss\lib\container.js:192:28
    at E:\gitlab\ZZY-Activities\node_modules\postcss\lib\container.js:148:26
    at Rule.each (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\container.js:114:22)
    at Rule.walk (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\container.js:147:21)
    at E:\gitlab\ZZY-Activities\node_modules\postcss\lib\container.js:150:32
    at Root.each (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\container.js:114:22)
    at Root.walk (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\container.js:147:21)
    at Root.walkDecls (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\container.js:190:25)
    at E:\gitlab\ZZY-Activities\node_modules\postcss-colormin\dist\index.js:73:20
    at LazyResult.run (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\lazy-result.js:274:20)
    at LazyResult.asyncTick (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\lazy-result.js:189:32)
    at LazyResult.asyncTick (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\lazy-result.js:201:22)
    at LazyResult.asyncTick (E:\gitlab\ZZY-Activities\node_modules\postcss\lib\lazy-result.js:201:22)
 @ ./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?{"min
imize":true,"sourceMap":true}!./~/vue-loader/lib/style-compiler?{"id":"data-v-409ffe34","scoped":true,"hasInlin
eConfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/components/Hello.vue 4:14-311
 @ ./src/components/Hello.vue
 @ ./src/router/index.js
 @ ./src/main.js`

**Comment by MarvinXu** [comment]
![image](https://cloud.githubusercontent.com/assets/7382357/24914911/48a09724-1f08-11e7-80db-b5d3326ce1c4.png)
could you help me find the problem ?

**Comment by MarvinXu** [comment]
I reinstalled all my node-modules, and it worked.
